### ISSUE TITLE
Bridge gfx seemingly doesn't appear sometimes

### ISSUE THREAD

**Issue by kittenchilly** [Meowlala/BOIStageAPI15#10]
I even use GridGFX():SetBridges(), but it happens if you don't do it as well and specify the bridges in the main file. The weird thing is that it seems to only happen on some floors and not others. This really impacts a mod I help made, and would really like if it got fixed. This is completely visual, and bridges can still be walked on however

**Comment by Meowlala** [comment]
Have you updated your bridge sprites to the new format in Repentance? They need to be arranged like they would be on a rock sheet. Alternatively, you can include them in your rocks.

**Comment by kittenchilly** [comment]
Yes, I have. I have tried both options and the problem still happens.

**Comment by Meowlala** [comment]
A reproduction example would help. Bridges are fully functional in the few mods I've tested.

**Comment by SunilB-1** [comment]
i think they're still broken in the few floors stageapi uses (i.e. catacombs, necropolis and utero), i've mentioned it in the fiend folio server and other people seem to experience it too (i just checked and it does happen with fiend folio disabled so it must come from stageapi)
