### ISSUE TITLE
What's with the hidden floors?

### ISSUE THREAD

**Issue by VoxNiphili** [Meowlala/BOIStageAPI15#107]
Seriously, why is the Lab, the "Morbiusreal" (what I call the Morbing Floor), and the Stony Floor all hidden? Especially the lab. Iteachvader's "Win The Race" fits it so well somehow.

**Comment by Meowlala** [comment]
Those stages are added by Fiend Folio, not StageAPI.

**Comment by VoxNiphili** [comment]
ah, apologies.
