### ISSUE TITLE
StageAPI's custom boss intro sound doesn't play

### ISSUE THREAD

**Issue by Jonathing** [Meowlala/BOIStageAPI15#13]
Hello! First of all, congrats on even getting this mod updated to Repentance! It's a really complicated one and just by looking at the Lua code, there's a lot going on.

Now for the issue. Whenever I enter a boss room in the game, the castle portcullis sound effect does not play at all. Obviously this is because StageAPI replaced Rebirth's `castleportcullis.wav` with an audio file that's completely empty, but I assume that's for the sake of working with the sfx manager.

Right now I'm working around this by commenting out everything in `main.lua` relating to the custom boss intro (i.e. lines 7172-7175) and the two `castleportcullis.wav` files used by StageAPI so Repentance can go back to using its own boss intro sound.

**Comment by Jonathing** [comment]
shit, for some reason my browser decided to submit this issue before I ever typed anything. Let's try that again.

**Comment by Jonathing** [comment]
There we go. Sorry about that! Hasn't happened before.

**Comment by DarkestSentinel** [comment]
Not a stage api dev, but this very likely has to do with currently repentance api's biggest bug. Custom modded sounds are completely broken, so when it tries to play the custom castleportcullis sound no sound will play. Hope this issue will be fixed with an upcoming repentance update

**Comment by Jonathing** [comment]
@DarkestSentinel That makes more sense. I'll just keep using my workaround until the issue gets fixed. Custom sounds are pretty damn important.

**Comment by Jonathing** [comment]
This got fixed indirectly by Repentance version 1.7.5.
