### ISSUE TITLE
Greed mode

### ISSUE THREAD

**Issue by Vd6563RUS** [Meowlala/BOIStageAPI15#174]
I have a similar music issue that triggers in catacombs necropolis and utero. The only music mods I have are antibirth music+++ and flash sounds and music, and I tested this problem with the aforementioned mods disabled. Basically, boss themes (both) and the calm do not play, stage theme restarts instead (this does not happen in normal runs). This sucks
Oh and I must mention, all jingles work and boss theme does in fact play when you fight angel in angel room. Shop theme also works just fine

**Comment by kittenchilly** [comment]
Should be fixed in latest version.
