### ISSUE TITLE
Chapters 2 and 3 (possibly others) alt rooms titles not showing

### ISSUE THREAD

**Issue by maddoodles** [Meowlala/BOIStageAPI15#18]
Hello, not sure if the issue is known or has been reported much yet but I have noticed that when starting Catacombs or Necropolis (so far), the stage name will not display, just a "I" or "II".

**Comment by Meowlala** [comment]
This is a known unsolvable issue. It's either custom stages display Catacombs II, or Catacombs displays just "II".
