### ISSUE TITLE
Cant donwload latest version of stage api from github?

### ISSUE THREAD

**Issue by xXTeMmiE07Xx** [Meowlala/BOIStageAPI15#185]
i came here from the steam mod page after i clicked on the link that said this is where the latest mod version would be. But every where i look and no matter what i donwload it always says version 1.5 and i cant play with it since its required for a mod. 
ive looked trough other issues and one person also asked why is that the case. 
Where can i downlad the latest version then?

**Comment by epfly6** [comment]
Code -> Download zip

**Comment by xXTeMmiE07Xx** [comment]
![image](https://github.com/Meowlala/BOIStageAPI15/assets/70447629/ce7ad9af-99a3-467b-9b78-e630075fc313)
still dosent work?? ive tried this a few times already with no results

**Comment by epfly6** [comment]
How did you unpacked archive?

**Comment by xXTeMmiE07Xx** [comment]
*supposed

**Comment by epfly6** [comment]
> i just unziped a file called "BOIStageAPI15-master.zip" into my mods folder to check if thats the correct version whats weird is that in metadata.xml it does say version 2.29 but ingame when i start a run it gives me this warning and fiend folio enemies dont work

Is there folder in unpacked folder?

**Comment by xXTeMmiE07Xx** [comment]
> > i just unziped a file called "BOIStageAPI15-master.zip" into my mods folder to check if thats the correct version whats weird is that in metadata.xml it does say version 2.29 but ingame when i start a run it gives me this warning and fiend folio enemies dont work
> 
> Is there folder in unpacked folder?

checked again nothing in there

**Comment by epfly6** [comment]
> ![whatsinthezip](https://private-user-images.githubusercontent.com/70447629/321347312-29a4d4b8-fc18-4ac7-b2a4-ced479f5b8e7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI3NzI0MjMsIm5iZiI6MTcxMjc3MjEyMywicGF0aCI6Ii83MDQ0NzYyOS8zMjEzNDczMTItMjlhNGQ0YjgtZmMxOC00YWM3LWIyYTQtY2VkNDc5ZjViOGU3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEwVDE4MDIwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQxZmEyMjE2MGQ3OTA2ZTYwZGFjN2U1NjU4ODMxMTM5MDUwN2NmNTViMmM1NGE5MzI2ZjAwZjdhOTAyN2Q5ZjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gYpY1nmb8DqEeVD1NW76v8YIEgy6FPM_-XL19l18ieM) this is whats in the zip after donwloading like u said ![andwhatsinsidethefolderthatwasinsidethezip](https://private-user-images.githubusercontent.com/70447629/321347778-2c63053f-84ff-45cc-a702-8edfb6e82e3e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI3NzI0MjMsIm5iZiI6MTcxMjc3MjEyMywicGF0aCI6Ii83MDQ0NzYyOS8zMjEzNDc3NzgtMmM2MzA1M2YtODRmZi00NWNjLWE3MDItOGVkZmI2ZTgyZTNlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEwVDE4MDIwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWViZDU3ZjI3NzcyMzBkZjM3MGM2YjJlYmRmNzc4M2RkYWU0ZDA1NGU0MjUwNTI4NGM5NTA0YWIwZTNmMWY2YWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.sHOxEjPgmDIqNuNsOgkT2cTrb2h0DjE8TxGkQc6UYPQ) and the things that were inside the folder from the zip (what i put in the mods folder)

I need from mods folder, not downloads

**Comment by xXTeMmiE07Xx** [comment]
![modsfolderone](https://github.com/Meowlala/BOIStageAPI15/assets/70447629/6d91b48a-0586-4e13-83fb-b8723fe42656)
here

**Comment by xXTeMmiE07Xx** [comment]
> > ![whatsinthezip](https://private-user-images.githubusercontent.com/70447629/321347312-29a4d4b8-fc18-4ac7-b2a4-ced479f5b8e7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI3NzI0MjMsIm5iZiI6MTcxMjc3MjEyMywicGF0aCI6Ii83MDQ0NzYyOS8zMjEzNDczMTItMjlhNGQ0YjgtZmMxOC00YWM3LWIyYTQtY2VkNDc5ZjViOGU3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEwVDE4MDIwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQxZmEyMjE2MGQ3OTA2ZTYwZGFjN2U1NjU4ODMxMTM5MDUwN2NmNTViMmM1NGE5MzI2ZjAwZjdhOTAyN2Q5ZjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gYpY1nmb8DqEeVD1NW76v8YIEgy6FPM_-XL19l18ieM) this is whats in the zip after donwloading like u said ![andwhatsinsidethefolderthatwasinsidethezip](https://private-user-images.githubusercontent.com/70447629/321347778-2c63053f-84ff-45cc-a702-8edfb6e82e3e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI3NzI0MjMsIm5iZiI6MTcxMjc3MjEyMywicGF0aCI6Ii83MDQ0NzYyOS8zMjEzNDc3NzgtMmM2MzA1M2YtODRmZi00NWNjLWE3MDItOGVkZmI2ZTgyZTNlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEwVDE4MDIwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWViZDU3ZjI3NzcyMzBkZjM3MGM2YjJlYmRmNzc4M2RkYWU0ZDA1NGU0MjUwNTI4NGM5NTA0YWIwZTNmMWY2YWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.sHOxEjPgmDIqNuNsOgkT2cTrb2h0DjE8TxGkQc6UYPQ) and the things that were inside the folder from the zip (what i put in the mods folder)
> 
> I need from mods folder, not downloads

so is everything alr?

**Comment by xXTeMmiE07Xx** [comment]
bro just please help me i dont want to redo my whole mod list 
i just want to play the damm game with the latest versions of mods

**Comment by epfly6** [comment]
> > I need from mods folder, not downloads
> 
> so is everything alr?

yes

**Comment by xXTeMmiE07Xx** [comment]
> > > I need from mods folder, not downloads
> > 
> > 
> > so is everything alr?
> 
> yes

can you even donwload the correct version from github to confirm it works or is it just a problem on my side? if it does could you send me that copy?
