### ISSUE TITLE
idk, got this whilst loading a save, was in Boiler stage.

### ISSUE THREAD

**Issue by VoxNiphili** [Meowlala/BOIStageAPI15#186]
"MC_PRE_ROOM_ENTITY_SPAWN" from "StageAPI" failed: ...eapi15_1348031964/scripts/stageapi/stage/customstage.lua:173: attempt to index a nil value (field 'Rooms')
Stack Traceback:
  ...eapi15_1348031964/scripts/stageapi/stage/customstage.lua:173: in function 'WillOverrideRoom'
  ...tageapi15_1348031964/scripts/stageapi/core/callbacks.lua:226: in function 'ShouldOverrideRoom'
  ...tageapi15_1348031964/scripts/stageapi/core/callbacks.lua:1342: in function at line 1332

Note, Boiler is from https://steamcommunity.com/sharedfiles/filedetails/?id=2974704582 .

**Comment by guwahavel** [comment]
Closing this bc its more of a Fall from Grace issue than a Stage API issue
