### ISSUE TITLE
mirror room in Boiler was replace by a normal catacombs room

### ISSUE THREAD

**Issue by yq28** [Meowlala/BOIStageAPI15#193]
mirror room in Boiler (from FFG mod) was replaced by a normal catacombs room and when I got into Boiler, my console reported some errors:
"MC_POST_NEW_ROOM" from "StageAPI" failed: ...geapi15_1348031964/scripts/stageapi/room/roomHandler.lua:356: attempt to index a nil value (local 'chosen')
Stack Traceback:
  ...geapi15_1348031964/scripts/stageapi/room/roomHandler.lua:356: in function 'ChooseRoomLayout'
  ...tageapi15_1348031964/scripts/stageapi/room/levelRoom.lua:387: in function 'GetLayout'
  ...tageapi15_1348031964/scripts/stageapi/room/levelRoom.lua:181: in function 'Init'
  ...stageapi15_1348031964/scripts/stageapi/library/class.lua:34: in function 'LevelRoom'
  ...eapi15_1348031964/scripts/stageapi/stage/customstage.lua:574: in function at line 484
  ...eapi15_1348031964/scripts/stageapi/stage/customstage.lua:688: in function 'GenerateLevel'
  ...tageapi15_1348031964/scripts/stageapi/core/callbacks.lua:1112: in function at line 855
![屏幕截图 2024-10-10 185416](https://github.com/user-attachments/assets/e1a9d98c-befe-4926-97a3-a7d6b6cc1173)

**Comment by guwahavel** [comment]
Closing this bc its more of a Fall from Grace issue than a Stage API issue
