### ISSUE TITLE
Subplayer characters make StageAPI.GetDefaultLevelMap() initially return nil

### ISSUE THREAD

**Issue by filloax** [Meowlala/BOIStageAPI15#23]
After testing it seems that with characters that have a SubPlayer (J&E and Tainted Forgotten) StageAPI.GetDefaultLevelMap() returns nil for the first floor, until the first stage change (either normally by trapdoor or via command, either to a normal stage or StageAPI one); this leads to bugs in various functions in StageAPI that use that function.

**Comment by filloax** [comment]
This could also be related to save-exit -> load breaking in custom floors more than usual, with this error on room load that breaks the loading:
`[INFO] - [StageAPI] Error in "PostRoomLoad" call: ...mmon\The Binding of Isaac Rebirth/mods/stageapi/main.lua:11364: attempt to index a nil value (local 'levelMap')`

**Comment by Meowlala** [comment]
Let me know if the latest commit resolves this issue, it has in my tests.

**Comment by filloax** [comment]
This did fix seemingly both issues
